name: pastexam-dev

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    image: pastexam-frontend-dev:latest
    container_name: pastexam-dev-frontend
    ports:
      # - "5173:80"
      - "24678:24678"
    env_file:
      - ../frontend/.env
    volumes:
      - /app/node_modules
      - ../frontend:/app
    networks:
      - app_network

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile.dev
    image: pastexam-backend-dev:latest
    container_name: pastexam-dev-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    # ports:
    #   - "8000:8000"
    volumes:
      - /app/.venv
      - ../backend:/app
    env_file:
      - ../backend/.env
    networks:
      - app_network

  worker:
    image: pastexam-backend-dev:latest
    container_name: pastexam-dev-worker
    command: arq app.worker.WorkerSettings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    env_file:
      - ../backend/.env
    networks:
      - app_network

  db:
    image: postgres:15.14-alpine3.22
    container_name: pastexam-dev-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: pastexam-dev-minio
    command: server /data --console-address ":9001"
    # ports:
    #   - "9000:9000"
    #   - "9001:9001" # 9000 for S3 API, 9001 for MinIO Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7.4.5-alpine3.21
    container_name: pastexam-dev-redis
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  nginx:
    image: nginx:1.29.2
    container_name: pastexam-dev-nginx
    ports:
      - "8080:8080"
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - minio
    networks:
      - app_network

networks:
  app_network:
    name: pastexam-dev-network
    driver: bridge

volumes:
  pg_data:
    name: pastexam-postgres-data
  minio_data:
    name: pastexam-minio-data
  redis_data:
    name: pastexam-redis-data
